#!/bin/sh

cpu=4
#vf="-filter:v scale=-1:720:flags=lanczos"
#vf="-filter:v scale=iw/2:ih/2:flags=lanczos"
cv="libaom-av1 -cpu-used $cpu -crf 30 -b:v 0"
fps=$(ffprobe -show_streams "$1" 2>&1 | grep fps | awk '{split($0,a,"fps")}END{print a[1]}' | awk '{print $NF}')
key=$(printf '%.0f' $(bc <<< "100*$fps"))

echo "CPU: $cpu"
echo "FPS: $fps"
echo "KF:  $key"

ffmpeg -v quiet -stats -i "$1" -passlogfile "$1" -pass 1 -c:v $cv $vf -sc_threshold 0 -g $key -keyint_min $key -pix_fmt yuv420p10le -row-mt 1 -an -f null -
#cpulimit -p $! -l 100

ffmpeg -v quiet -stats -i "$1" -passlogfile "$1" -pass 2 -c:v $cv $vf -sc_threshold 0 -g $key -keyint_min $key -pix_fmt yuv420p10le -row-mt 1 -c:a copy -movflags +faststart "$1.AV1.mp4"
#cpulimit -p $! -l 100

rm "$1-0.log"

# from old script:
# params="-v 24 -stats -i \"$1\" -passlogfile \"$1\" -c:v libaom-av1 -cpu-used 0 -crf 30 -b:v 0 -row-mt 1 -g $kf -aom-params enable-qm=1"
