#!/bin/bash

export PATH=/usr/local/bin:$HOME/.local/bin:$PATH
backup-prepare

source ~/.config/borg.conf
export BORG_PROGRESS="--stats --progress -v"

borg create $BORG_PROGRESS -xC zstd,22 \
-e .DS_Store \
-e $HOME/.cache \
-e $HOME/Downloads \
-e $HOME/Library \
-e $HOME/Projects \
-e $HOME/.Trash \
::'{now:%Y-%m-%d}' $HOME

# borg prune --keep-daily 100
borg compact --threshold 0 --cleanup-commits

# borg prune --keep-daily 7 --keep-weekly 8 --keep-monthly 12
