#!/bin/sh

ssh ssh-proxy ./get_hosts.sh | column
read -p "enter host: " host

ssh ssh-proxy ./get_ip.sh $host
read -p "ip address: " ip

echo "adding ip to en1..."
sudo ifconfig en1 alias $ip/32

echo "binding geacmed to local ip..."
lh='162.55.188.203'
ssh \
-L $ip:8009:$lh:8009 -L $ip:1098:$lh:1098 -L $ip:1099:$lh:1099 -L $ip:8080:$lh:8080 -L $ip:8083:$lh:8083 \
-L $ip:4444:$lh:4444 -L $ip:8093:$lh:8093 -L $ip:4445:$lh:4445 -L $ip:3873:$lh:3873 -L $lh:5433:$lh:5433 \
ssh-proxy ssh \
-L $lh:8009:$ip:8009 -L $lh:1098:$ip:1098 -L $lh:1099:$ip:1099 -L $lh:8080:$ip:8080 -L $lh:8083:$ip:8083 \
-L $lh:4444:$ip:4444 -L $lh:8093:$ip:8093 -L $lh:4445:$ip:4445 -L $lh:3873:$ip:3873 -L 127.0.0.1:5433:$lh:5432 \
$host

echo "removing $ip from en1..."
sudo ifconfig en1 -alias $ip

echo "done"
