#!/bin/sh
CRF=22

function run_ffmpeg {
	#quiet="-v quiet -nostdin"
	FILE="VP9_${2}_$1.mp4"
	ffmpeg -y -i "$1" -passlogfile "$1" $quiet -c:v libvpx-vp9 -pix_fmt yuv420p10le -pass 1 $3 $4 -f null -
	ffmpeg -y -i "$1" -passlogfile "$1" $quiet -c:v libvpx-vp9 -pix_fmt yuv420p10le -pass 2 $3 $4 "$FILE"
	rm "$1-0.log"
}

opt1="-quality good -threads 1 -profile:v 2 -lag-in-frames 25 -b:v 0 -crf $CRF -g 240"
opt2="-cpu-used 4 -auto-alt-ref 0 -aq-mode 3 -tile-rows 0 -tile-columns 0 -enable-tpl 1 -row-mt 0"
#run_ffmpeg "$1" $CRF "$opt1" "$opt2"

opt1="-quality good -threads 4 -profile:v 2 -lag-in-frames 25 -crf $CRF -b:v 0 -g 240"
opt2="-cpu-used 4 -auto-alt-ref 1 -arnr-maxframes 7 -arnr-strength 4 -aq-mode 2 -tile-rows 0 -tile-columns 1 -enable-tpl 1 -row-mt 1"
#run_ffmpeg "$1" $CRF "$opt1" "$opt2"

# cpu-used 4 to 0 / CRF was 15
opt1="-quality good -threads 8 -profile:v 2 -lag-in-frames 25 -crf $CRF -b:v 0 -g 300"
#opt2="-keyint_min 300 -cpu-used 0 -auto-alt-ref 1 -arnr-maxframes 0 -aq-mode 4 -tile-rows 0 -tile-columns 0 -enable-tpl 1 -row-mt 1"
opt2="-keyint_min 300 -cpu-used 2 -auto-alt-ref 1 -arnr-maxframes 0 -aq-mode 4 -tile-rows 0 -tile-columns 0 -enable-tpl 1 -row-mt 1"
run_ffmpeg "$1" $CRF "$opt1" "$opt2"
